export const researcherType = [
  {
    id: 1,
    title: "Academic Researcher",
    description: "(University faculty, postdocs, or PhD students engaged in scholarly research)",
    features: [
      "Access academic journals, papers, and collaboration opportunities.",
      "Track citations and impact metrics.",
      "Connect with peers and experts in your field.",
    ],
  },
  {
    id: 2,
    title: "Industry Researcher",
    description: "(Professionals conducting research within corporate or industrial settings)",
    features: [
      "Access to market research reports and industry publications.",
      "Collaboration with industry experts and stakeholders.",
      "Opportunities for innovation and product development.",
    ],
  },
  {
    id: 3,
    title: "Independent Researcher",
    description:
      "(Freelancers or self-funded researchers working outside traditional institutions)",
    features: [
      "Access to a variety of research databases and resources.",
      "Opportunities to publish work in open-access journals.",
      "Network with other independent researchers.",
    ],
  },
  {
    id: 4,
    title: "Student Researcher",
    description: "(Undergraduate or master's students engaged in research projects)",
    features: [
      "Access to educational resources and research tools.",
      "Guidance on research methodologies and best practices.",
      "Opportunities to present research at student conferences.",
    ],
  },
];
export const researchers = [
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
];

export const popularSubjectAreas = [
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Computer Science",
  "Economics",
  "History",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Philosophy",
  "Political Science",
  "Literature",
  "Art History",
  "Linguistics",
  "Astronomy",
  "Geography",
  "Environmental Science",
  "Urban Planning",
  "Public Health",
  "Education",
  "Business",
  "Law",
  "Engineering",
  "Music",
  "Theater",
  "Film Studies",
  "Religious Studies",
  "Dance",
  "Architecture",
  "Archaeology",
  "Neuroscience",
  "Mathematical Economics",
  "Industrial Engineering",
  "Sustainability",
  "Education Technology",
  "Modern History",
  "Health Communication",
  "Digital Humanities",
  "Cultural Studies",
  "Social Work",
  "Environmental Engineering",
  "Public Policy",
  "Gender Studies",
  "Ethnic Studies",
  "Comparative Literature",
  "Public Administration",
  "Food Science",
  "Environmental Policy",
  "African American Studies",
  "Latin American Studies",
  "Eastern Philosophy",
  "European History",
  "Asian Studies",
  "Marine Biology",
  "Development Studies",
  "Museum Studies",
  "Health Education",
  "Behavioral Economics",
  "International Relations",
  "Genetics",
  "Molecular Biology",
  "Biochemistry",
  "Organic Chemistry",
  "Inorganic Chemistry",
  "Physical Chemistry",
  "Quantum Physics",
  "Astrophysics",
  "Geophysics",
  "Applied Mathematics",
  "Statistics",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Software Engineering",
  "Web Development",
  "Mobile App Development",
  "Game Design",
  "Virtual Reality",
  "Augmented Reality",
  "Robotics",
  "Nanotechnology",
  "Biotechnology",
  "Microeconomics",
  "Macroeconomics",
  "Financial Economics",
  "Ancient History",
  "Medieval History",
  "Renaissance History",
  "World History",
  "Military History",
  "Social Psychology",
  "Cognitive Psychology",
  "Developmental Psychology",
  "Clinical Psychology",
  "Forensic Psychology",
  "Organizational Psychology",
  "Educational Psychology",
  "Sports Psychology",
  "Medical Sociology",
  "Urban Sociology",
  "Rural Sociology",
  "Environmental Sociology",
  "Cultural Anthropology",
  "Linguistic Anthropology",
  "Physical Anthropology",
  "Archaeological Anthropology",
  "Logic",
  "Ethics",
  "Metaphysics",
  "Epistemology",
  "Political Philosophy",
  "Comparative Politics",
  "International Politics",
  "Public Administration",
  "Classical Literature",
  "Modern Literature",
  "World Literature",
  "Creative Writing",
  "Poetry",
  "Drama",
  "Renaissance Art",
  "Modern Art",
  "Contemporary Art",
  "Sociolinguistics",
  "Psycholinguistics",
  "Computational Linguistics",
  "Cosmology",
  "Planetary Science",
  "Human Geography",
  "Physical Geography",
  "Cartography",
  "Ecology",
  "Conservation Biology",
  "Climate Science",
  "City Planning",
  "Regional Planning",
  "Transportation Planning",
  "Epidemiology",
  "Biostatistics",
  "Health Policy",
  "Special Education",
  "Early Childhood Education",
  "Higher Education",
  "Adult Education",
  "Marketing",
  "Finance",
  "Human Resource Management",
  "Operations Management",
  "International Business",
  "Entrepreneurship",
  "Corporate Law",
  "Criminal Law",
  "Constitutional Law",
  "International Law",
  "Intellectual Property Law",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Music Theory",
  "Music Composition",
  "Ethnomusicology",
  "Musical Performance",
  "Theater Direction",
  "Playwriting",
  "Stage Design",
  "Cinematography",
  "Film Production",
  "Screenwriting",
  "Comparative Religion",
  "Theology",
  "Biblical Studies",
  "Islamic Studies",
  "Buddhist Studies",
  "Choreography",
  "Dance History",
  "Landscape Architecture",
  "Interior Design",
  "Urban Design",
  "Classical Archaeology",
  "Underwater Archaeology",
  "Cognitive Neuroscience",
  "Computational Neuroscience",
  "Systems Engineering",
  "Renewable Energy",
  "Sustainable Agriculture",
  "Green Technology",
  "Ancient Near Eastern Studies",
  "Mesoamerican Studies",
  "African Studies",
  "Middle Eastern Studies",
  "South Asian Studies",
  "East Asian Studies",
  "Southeast Asian Studies",
  "Pacific Island Studies",
  "Caribbean Studies",
  "Scandinavian Studies",
  "Slavic Studies",
  "Celtic Studies",
  "Oceanography",
  "Hydrology",
  "Meteorology",
  "Seismology",
  "Volcanology",
  "Paleontology",
  "Mineralogy",
  "Petrology",
  "Geomorphology",
  "Remote Sensing",
  "Geographic Information Systems",
  "Demography",
  "Criminology",
  "Victimology",
  "Penology",
  "Social Gerontology",
  "Child Development",
  "Family Studies",
  "Human Sexuality",
  "Forensic Science",
  "Toxicology",
  "Pharmacology",
  "Immunology",
  "Virology",
  "Parasitology",
  "Mycology",
  "Entomology",
  "Ornithology",
  "Ichthyology",
  "Herpetology",
  "Mammalogy",
  "Botany",
  "Zoology",
  "Library and Information Science",
  "Library Science",
];

export const feedRecentCard = [
  {
    fullname: "Dr. Sarah Johnson",
    followers: "100",
    title: "Innovations in Renewable Energy Storage",
    privacy: "public",
  },
  {
    fullname: "Dr. Sarah Johnson",
    followers: "100",
    title: "Innovations in Renewable Energy Storage",
    privacy: "public",
  },
  {
    fullname: "Dr. Sarah Johnson",
    followers: "100",
    title: "Innovations in Renewable Energy Storage",
    privacy: "public",
  },
];
