export const researcherType = [
  {
    id: 1,
    title: "Academic Researcher",
    description: "(University faculty, postdocs, or PhD students engaged in scholarly research)",
    features: [
      "Access academic journals, papers, and collaboration opportunities.",
      "Track citations and impact metrics.",
      "Connect with peers and experts in your field.",
    ],
  },
  {
    id: 2,
    title: "Academic Researchr",
    description: "(University faculty, postdocs, or PhD students engaged in scholarly research)",
    features: [
      "Access academic journals, papers, and collaboration opportunities.",
      "Track citations and impact metrics.",
      "Connect with peers and experts in your field.",
    ],
  },
  {
    id: 3,
    title: "Academic Resarcher",
    description: "(University faculty, postdocs, or PhD students engaged in scholarly research)",
    features: [
      "Access academic journals, papers, and collaboration opportunities.",
      "Track citations and impact metrics.",
      "Connect with peers and experts in your field.",
    ],
  },
  {
    id: 4,
    title: "Academi Researcher",
    description: "(University faculty, postdocs, or PhD students engaged in scholarly research)",
    features: [
      "Access academic journals, papers, and collaboration opportunities.",
      "Track citations and impact metrics.",
      "Connect with peers and experts in your field.",
    ],
  },
];

export const researchers = [
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
];

export const popularSubjectAreas = [
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Computer Science",
  "Economics",
  "History",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Philosophy",
  "Political Science",
  "Literature",
  "Art History",
  "Linguistics",
  "Astronomy",
  "Geography",
  "Environmental Science",
  "Urban Planning",
  "Public Health",
  "Education",
  "Business",
  "Law",
  "Engineering",
  "Music",
  "Theater",
  "Film Studies",
  "Religious Studies",
  "Dance",
  "Architecture",
  "Archaeology",
  "Neuroscience",
  "Mathematical Economics",
  "Industrial Engineering",
  "Sustainability",
  "Education Technology",
  "Modern History",
  "Health Communication",
  "Digital Humanities",
  "Cultural Studies",
  "Social Work",
  "Environmental Engineering",
  "Public Policy",
  "Gender Studies",
  "Ethnic Studies",
  "Comparative Literature",
  "Public Administration",
  "Food Science",
  "Environmental Policy",
  "African American Studies",
  "Latin American Studies",
  "Eastern Philosophy",
  "European History",
  "Asian Studies",
  "Marine Biology",
  "Development Studies",
  "Museum Studies",
  "Health Education",
  "Behavioral Economics",
  "International Relations",
];
