export const researcherType = [
  {
    id: 1,
    title: "Academic Researcher",
    description: "(University faculty, postdocs, or PhD students engaged in scholarly research)",
    features: [
      "Access academic journals, papers, and collaboration opportunities.",
      "Track citations and impact metrics.",
      "Connect with peers and experts in your field.",
    ],
  },
  {
    id: 2,
    title: "Industry Researcher",
    description: "(Professionals conducting research within corporate or industrial settings)",
    features: [
      "Access to market research reports and industry publications.",
      "Collaboration with industry experts and stakeholders.",
      "Opportunities for innovation and product development.",
    ],
  },
  {
    id: 3,
    title: "Independent Researcher",
    description:
      "(Freelancers or self-funded researchers working outside traditional institutions)",
    features: [
      "Access to a variety of research databases and resources.",
      "Opportunities to publish work in open-access journals.",
      "Network with other independent researchers.",
    ],
  },
  {
    id: 4,
    title: "Student Researcher",
    description: "(Undergraduate or master's students engaged in research projects)",
    features: [
      "Access to educational resources and research tools.",
      "Guidance on research methodologies and best practices.",
      "Opportunities to present research at student conferences.",
    ],
  },
];
export const researchers = [
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
  { name: "Dr. Sarah Johnson", publications: 10, followers: 100 },
];

export const popularSubjectAreas = [
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Computer Science",
  "Economics",
  "History",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Philosophy",
  "Political Science",
  "Literature",
  "Art History",
  "Linguistics",
  "Astronomy",
  "Geography",
  "Environmental Science",
  "Urban Planning",
  "Public Health",
  "Education",
  "Business",
  "Law",
  "Engineering",
  "Music",
  "Theater",
  "Film Studies",
  "Religious Studies",
  "Dance",
  "Architecture",
  "Archaeology",
  "Neuroscience",
  "Mathematical Economics",
  "Industrial Engineering",
  "Sustainability",
  "Education Technology",
  "Modern History",
  "Health Communication",
  "Digital Humanities",
  "Cultural Studies",
  "Social Work",
  "Environmental Engineering",
  "Public Policy",
  "Gender Studies",
  "Ethnic Studies",
  "Comparative Literature",
  "Public Administration",
  "Food Science",
  "Environmental Policy",
  "African American Studies",
  "Latin American Studies",
  "Eastern Philosophy",
  "European History",
  "Asian Studies",
  "Marine Biology",
  "Development Studies",
  "Museum Studies",
  "Health Education",
  "Behavioral Economics",
  "International Relations",
];
